// <auto-generated />
namespace Movie_App.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Addnewratings : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Addnewratings));
        
        string IMigrationMetadata.Id
        {
            get { return "202307110900445_Add newratings"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
